# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ILYA\Desktop\Python\OTRS\classifier\interface\ui\train.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 255)
        MainWindow.setMaximumSize(QtCore.QSize(700, 255))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 131, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.label_2.setObjectName("label_2")
        self.ram_size_line = QtWidgets.QLineEdit(self.centralwidget)
        self.ram_size_line.setGeometry(QtCore.QRect(120, 30, 31, 20))
        self.ram_size_line.setText("")
        self.ram_size_line.setObjectName("ram_size_line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(156, 30, 51, 21))
        self.label_3.setObjectName("label_3")
        self.trainButton = QtWidgets.QPushButton(self.centralwidget)
        self.trainButton.setGeometry(QtCore.QRect(10, 190, 191, 23))
        self.trainButton.setObjectName("trainButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_4.setObjectName("label_4")
        self.gpu_mem_size_line = QtWidgets.QLineEdit(self.centralwidget)
        self.gpu_mem_size_line.setGeometry(QtCore.QRect(70, 60, 31, 20))
        self.gpu_mem_size_line.setText("")
        self.gpu_mem_size_line.setObjectName("gpu_mem_size_line")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 60, 101, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 90, 151, 31))
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 80, 221, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 121, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 81, 16))
        self.label_8.setObjectName("label_8")
        self.num_tickets_line = QtWidgets.QLineEdit(self.centralwidget)
        self.num_tickets_line.setGeometry(QtCore.QRect(120, 130, 81, 20))
        self.num_tickets_line.setText("")
        self.num_tickets_line.setObjectName("num_tickets_line")
        self.batch_size_line = QtWidgets.QLineEdit(self.centralwidget)
        self.batch_size_line.setGeometry(QtCore.QRect(120, 160, 81, 20))
        self.batch_size_line.setObjectName("batch_size_line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(209, 0, 31, 251))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.log = QtWidgets.QTextEdit(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(240, 10, 445, 231))
        self.log.setObjectName("log")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(10, 220, 191, 23))
        self.closeButton.setObjectName("closeButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Управление ресурсами"))
        self.label_2.setText(_translate("MainWindow", "Выделить программе"))
        self.label_3.setText(_translate("MainWindow", "гб ОЗУ"))
        self.trainButton.setText(_translate("MainWindow", "Запустить обучение"))
        self.label_4.setText(_translate("MainWindow", "Выделить"))
        self.label_5.setText(_translate("MainWindow", "видеопамяти (0-1)"))
        self.label_6.setText(_translate("MainWindow", "Параметры обучения модели"))
        self.label_7.setText(_translate("MainWindow", "Количество заявок"))
        self.label_8.setText(_translate("MainWindow", "Размер порции"))
        self.closeButton.setText(_translate("MainWindow", "Вернуться в главное меню"))

